# Generated by Django 4.2.19 on 2025-02-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
