# Generated by Django 4.2.19 on 2025-02-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
