# Generated by Django 4.2.19 on 2025-02-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
